version: '3.4'

services:
  soundwords:
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=db;User=soundwords;Database=soundwords;Password=secret;
      - DB_TYPE=MySQL
      - SITE_NAME=SoundWords
      - SITE_URL=http://localhost:45080
      - DebugMode=true
      - "META_DESCRIPTION=P&aring; sunneord.no kan du lytte til bibelundervisning fra for mer enn et halvt &aring;rhundre siden og til i dag. &quot;... lik et tre, plantet ved rennende bekker.&quot;"
      - "COMPANY_NAME=Foreningen Sunne ord"
      - "COMPANY_EMAIL=post@sunneord.no"
      - "SLOGAN=... lik et tre, plantet ved rennende bekker."
      - "PODCAST_CATEGORIES__0=Religion & Spirituality"
      - "PODCAST_SUBCATEGORIES__0=Christianity"
      - "PODCAST_CATEGORIES__1=A category"
      - "PODCAST_SUBCATEGORIES__1=A subcategory"
    ports:
      - "45080:80"
    volumes:
#      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
#      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ../lib/snd/public:/var/audio/public
      - ../lib/snd/restricted:/var/audio/restricted
      - ../custom:/var/custom

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=soundwords
      - MYSQL_USER=soundwords
      - MYSQL_PASSWORD=secret
#    volumes:
#      db-data:/var/lib/mysql

#volumes:
#  db-data: